//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyboardCoach {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceUpper {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceUpper() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyboardCoach.ResourceUpper", typeof(ResourceUpper).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string b {
            get {
                return ResourceManager.GetString("b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        internal static string backSlash {
            get {
                return ResourceManager.GetString("backSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string c {
            get {
                return ResourceManager.GetString("c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string comma {
            get {
                return ResourceManager.GetString("comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string d {
            get {
                return ResourceManager.GetString("d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string ee {
            get {
                return ResourceManager.GetString("ee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string eight {
            get {
                return ResourceManager.GetString("eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string equal {
            get {
                return ResourceManager.GetString("equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string f {
            get {
                return ResourceManager.GetString("f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string five {
            get {
                return ResourceManager.GetString("five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        internal static string four {
            get {
                return ResourceManager.GetString("four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        internal static string g {
            get {
                return ResourceManager.GetString("g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~.
        /// </summary>
        internal static string gravis {
            get {
                return ResourceManager.GetString("gravis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        internal static string h {
            get {
                return ResourceManager.GetString("h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string i {
            get {
                return ResourceManager.GetString("i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J.
        /// </summary>
        internal static string j {
            get {
                return ResourceManager.GetString("j", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        internal static string k {
            get {
                return ResourceManager.GetString("k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string l {
            get {
                return ResourceManager.GetString("l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string m {
            get {
                return ResourceManager.GetString("m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _.
        /// </summary>
        internal static string minus {
            get {
                return ResourceManager.GetString("minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string n {
            get {
                return ResourceManager.GetString("n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        internal static string nine {
            get {
                return ResourceManager.GetString("nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        internal static string o {
            get {
                return ResourceManager.GetString("o", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !.
        /// </summary>
        internal static string one {
            get {
                return ResourceManager.GetString("one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string p {
            get {
                return ResourceManager.GetString("p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string point {
            get {
                return ResourceManager.GetString("point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        internal static string q {
            get {
                return ResourceManager.GetString("q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string r {
            get {
                return ResourceManager.GetString("r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string semicolon {
            get {
                return ResourceManager.GetString("semicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;.
        /// </summary>
        internal static string seven {
            get {
                return ResourceManager.GetString("seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^.
        /// </summary>
        internal static string six {
            get {
                return ResourceManager.GetString("six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string slash {
            get {
                return ResourceManager.GetString("slash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {.
        /// </summary>
        internal static string SquareBracketLeft {
            get {
                return ResourceManager.GetString("SquareBracketLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string SquareBracketRight {
            get {
                return ResourceManager.GetString("SquareBracketRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string t {
            get {
                return ResourceManager.GetString("t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string three {
            get {
                return ResourceManager.GetString("three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @.
        /// </summary>
        internal static string two {
            get {
                return ResourceManager.GetString("two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.
        /// </summary>
        internal static string u {
            get {
                return ResourceManager.GetString("u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        internal static string upperComma {
            get {
                return ResourceManager.GetString("upperComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        internal static string v {
            get {
                return ResourceManager.GetString("v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        internal static string w {
            get {
                return ResourceManager.GetString("w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string x {
            get {
                return ResourceManager.GetString("x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string y {
            get {
                return ResourceManager.GetString("y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        internal static string z {
            get {
                return ResourceManager.GetString("z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string zero {
            get {
                return ResourceManager.GetString("zero", resourceCulture);
            }
        }
    }
}
